name: Monorepo CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  # webapp-tests:
  #   name: Web App Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2
      
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '14'

  #     - name: Install dependencies
  #       run: npm install
  #       working-directory: web_app_directory

  #     - name: Run web app tests
  #       run: npm test
  #       working-directory: web_app_directory

  k-s-tests:
    name: Data Science Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run data science tests
        run: pytest tests/

  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps: